title: Cynthia Clifford # your name (or website title) here
logo: "/images/mypic.png?raw=true/" # your photo (or logo) here
<a href="https://www.linkedin.com/in/cynthia-a-clifford/">View My LinkedIn Profile</a> 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Math teacher turned data analyst. <br>
  I love finding patterns in data, and solving hard problems.   <br>
  I am passionate about using data to create actionable insights and inform decision-making.
  I'm a mechanical engineer turned international school math teacher. 
  I've lived in 13 countries and traveled to many more. 
  <br>Next stop: a data analyst role and a return home to the Mad River Valley in Vermont. <br><br>
I’ve gained valuable experience through work projects, personal projects, and have a strong foundation in tools and technologies such as Excel/Sheets, Tableau, Excel, and R, and SQL. And I’m currently learning Python.
I have a Bachelor's in Mechanical Engineering and a Master's in Education. I have worked as an engineer and as an international school math educator. Through those experiences, I’ve developed strong analytical and problem-solving skills, as well as excellent presentation and communication skills. I know how to communicate complex ideas in terms that are understandable. 
I’ve lived and worked in 12 countries outside of the US, demonstrating my flexibility, curiosity, and adaptability. I’ve also been a team leader and department head, and teacher trainer. My experience in leadership has strengthened my analytical and problem-solving abilities, and my desire to use data to improve programs. I want to use these skills to transition into an analytics role.
I am excited to bring my analytical skills, leadership experience, and education to a data analyst role. I’m a self-motivated life-long learner and will continue my professional development in this field because it is FUN. I am confident that my combination of education and experience makes me a strong candidate, and I am eager to use my skills to help organizations achieve their goals.

  
  <a href="https://www.linkedin.com/in/cynthia-a-clifford/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



  
 
