title: Cynthia Clifford # your name (or website title) here
logo: "/images/mypic.png?raw=true/" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven educator, 
  <br>Transitioning to data analytics. <br>
  I love finding patterns in data.   <br>
  <br> I am a mechanical engineer turned international school math and stats teacher. Now I'm transitioning to data. 
 I have lived in 12 countries and traveled to many more. The Mad River Valley in Vermont is home and I'm looking forward to moving back home and being closer to my son as I start my new data career.
 I love to hike, do yoga, read, cook, and scuba dive.
  <a href="https://www.linkedin.com/in/cynthia-a-clifford/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
