title: Cynthia Clifford # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven math educator transitioning to data analytics. <br>
  I love pattern finding patterns in data to make complex ideas understandable.  <br><br>
  <a href="https://www.linkedin.com/in/cynthia-a-clifford/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
